name: overwatch-bp
recipe: pantheon
config:
  framework: drupal9
  site: overwatch-bp
  id: c9b9a48d-48ae-47d0-9dba-784379228a8c
services:
  node:
    type: node
    build:
      - npm install
      - gulp
    globals:
      gulp-cli: latest
tooling:
  phpcs:
    service: appserver
    cmd: "/app/vendor/bin/phpcs --standard=Drupal,DrupalPractice"
    description: Run phpcs for given folder or file.
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  yarn:
    service: node
