_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: d7401bc9-622a-4fcc-9e89-af8683826399
name: Overwatch
mail: fredric@brightplum.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/522
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
